# This is a generated file. Not intended for manual editing.
services:
  discord:
    build:
      context: "D:\\source\\repos\\shoreline\\src\\Shoreline.Providers.Discord"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "shoreline.providers.discord:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "C:\\Users\\Aarons\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\source\\repos\\shoreline\\src\\Shoreline.Providers.Discord:/app:rw"
    - "D:\\source\\repos\\shoreline:/src:rw"
    - "C:\\Users\\Aarons\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\Aarons\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Aarons\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_25_20_55_07:/var/opt/rider-debugger:rw"
    working_dir: "/app"
